[build]
command = "bundle exec jekyll build"
publish = "_site"

[build.environment]
JEKYLL_ENV = "production"
RUBY_VERSION = "3.4.5"

[[plugins]]
package = "netlify-plugin-ruby"

[context.production.environment]
JEKYLL_ENV = "production"
